GO
USE QUANLYSTCOOPFOOD

SET DATEFORMAT DMY;

---------------------------------------------------PROCEDURE BANG KHACHHANG
--THÊM KHÁCH HÀNG
GO
CREATE PROC sp_ThemKH(@MAKH NVARCHAR(10), @HOKH NVARCHAR(30), @TENKH NVARCHAR(10), @SDT NVARCHAR(15),
						  @DCHI NVARCHAR(200), @DIEM INT)
AS
INSERT INTO [KHACHHANG](MAKH,HOKH,TENKH,SDT,DCHI,DIEM) VALUES (@MAKH,@HOKH,@TENKH,@SDT,@DCHI,@DIEM)
--XÓA KHÁCH HÀNG
GO
CREATE PROC sp_XoaKH(@MAKH NVARCHAR(10))
AS
	DELETE [KHACHHANG]
	WHERE MAKH=@MAKH
--SỬA KHÁCH HÀNG
GO
CREATE PROC sp_SuaKH(@MAKH NVARCHAR(10), @HOKH NVARCHAR(30), @TENKH NVARCHAR(10), @SDT NVARCHAR(15),
						  @DCHI NVARCHAR(200), @DIEM INT)
AS
	UPDATE [KHACHHANG]
	SET HOKH=@HOKH,TENKH=@TENKH,SDT=@SDT,DCHI=@DCHI,DIEM=@DIEM
	WHERE MAKH=@MAKH
--LẤY DANH SÁCH KHÁCH HÀNG
GO
CREATE PROC sp_LayDSKH
AS 
	SELECT * FROM [KHACHHANG]

---------------------------------------------------PROCEDURE BẢNG NHANVIEN
--THÊM NHANVIEN
GO
CREATE PROC sp_THEMNV(@MANV NVARCHAR(10), @HONV NVARCHAR(30), @TENNV NVARCHAR(10), @NGSINH DATE, 
						 @PHAI NVARCHAR(10), @DCHI NVARCHAR(200), @SDT NVARCHAR(15), @CMND NVARCHAR(9))
AS
INSERT INTO [NHANVIEN](MANV,HONV,TENNV,NGSINH,PHAI,DCHI,SDT,CMND) VALUES (@MANV,@HONV,@TENNV,@NGSINH,@PHAI,@DCHI,@SDT,@CMND)
--XÓA NHÂN VIÊN
GO
CREATE PROC sp_XOANV(@MANV NVARCHAR(10))
AS
	DELETE
	FROM [NHANVIEN]
	WHERE MANV=@MANV
--SỬA NHANVIEN
GO
CREATE PROC sp_SUANV(@MANV NVARCHAR(10), @HONV NVARCHAR(30), @TENNV NVARCHAR(10), @NGSINH DATE, 
						 @PHAI NVARCHAR(10), @DCHI NVARCHAR(200), @SDT NVARCHAR(15), @CMND NVARCHAR(9))
AS
	UPDATE [NHANVIEN]
	SET HONV=@HONV,TENNV=@TENNV, NGSINH=@NGSINH,PHAI=@PHAI,DCHI=@DCHI,SDT=@SDT,CMND=@CMND
	WHERE MANV=@MANV
--LẤY DANH SÁCH NHANVIEN
GO
CREATE PROC sp_LAYDSNV
AS
	SELECT * FROM [NHANVIEN]

---------------------------------------------------PROCEDURE BẢNG NHACUNGCAP
--THÊM NHÀ CUNG CẤP
GO
CREATE PROC sp_ThemNCC(@MANCC NVARCHAR(10), @TENNCC NVARCHAR(200), @DCHI NVARCHAR(200), @SDT NVARCHAR(15), @EMAIL NVARCHAR(50))
AS
	INSERT INTO [NHACUNGCAP] (MANCC,TENNCC,DCHI,SDT,EMAIL) VALUES (@MANCC,@TENNCC,@DCHI,@SDT,@EMAIL)
--XÓA NHÀ CUNG CẤP
GO
CREATE PROC sp_XOANCC(@MANCC NVARCHAR(10))
AS
	DELETE [NHACUNGCAP]
	WHERE MANCC=@MANCC

--SỬA NHÀ CUNG CẤP
GO
CREATE PROC sp_SuaNCC(@MANCC NVARCHAR(10), @TENNCC NVARCHAR(200), @DCHI NVARCHAR(200), @SDT NVARCHAR(15), @EMAIL NVARCHAR(50))
AS
	UPDATE [NHACUNGCAP]
	SET TENNCC=@TENNCC,DCHI=@DCHI,SDT=@SDT,EMAIL=@EMAIL
	WHERE MANCC=@MANCC

--LẤY NHÀ CUNG CẤP
GO
CREATE PROC sp_LayNCC
AS 
	SELECT * FROM [NHACUNGCAP]
---------------------------------------------------PROCEDURE BẢNG HÀNG HÓA
--THÊM HANGHOA
GO
CREATE PROC sp_THEMHH(@MAHH NVARCHAR(10), @MANCC NVARCHAR(10),@TENHH NVARCHAR(100), @LOAIHH NVARCHAR(40), 
						@SOLUONG INT, @DONGIA INT, @NGAYSX DATE, @HANSD DATE)
AS
	INSERT INTO [HANGHOA](MAHH,MANCC,TENHH,LOAIHH,SOLUONG,DONGIA,NGAYSX,HANSD)
		VALUES (@MAHH,@MANCC,@TENHH,@LOAIHH,@SOLUONG,@DONGIA,@NGAYSX,@HANSD)

--XÓA HANGHOA
GO
CREATE PROC sp_XOAHH(@MAHH NVARCHAR(10))
AS
	DELETE [HANGHOA]
	WHERE MAHH=@MAHH
--SỬA HANGHOA
GO
CREATE PROC sp_SUAHH(@MAHH NVARCHAR(10), @MANCC NVARCHAR(10),@TENHH NVARCHAR(100), @LOAIHH NVARCHAR(40), 
						@SOLUONG INT, @DONGIA INT, @NGAYSX DATE, @HANSD DATE)
AS
	UPDATE [HANGHOA]
	SET MANCC=@MANCC, TENHH=@TENHH,LOAIHH=@LOAIHH, SOLUONG=@SOLUONG,DONGIA=@DONGIA,NGAYSX=@NGAYSX,HANSD=@HANSD
	WHERE MAHH=@MAHH
--LẤY DANH SÁCH HANGHOA
GO
CREATE PROC sp_LAYDSHH
AS SELECT * FROM [HANGHOA]
---------------------------------------------------PROCEDURE BẢNG HÓA ĐƠN
--THÊM HÓA ĐƠN
GO
CREATE PROC sp_THEMHD(@MAHD NVARCHAR(10), @NGAYLAP DATE, @PTTHANHTOAN NVARCHAR(15), 
					   @MANV NVARCHAR(10), @MAKH NVARCHAR(10), @TIENKHACHTRA INT NULL)
AS
	INSERT INTO [HOADON](MAHD,NGAYLAP,PTTHANHTOAN,MANV,MAKH,TIENKHACHTRA) VALUES (@MAHD,@NGAYLAP,@PTTHANHTOAN,@MANV,@MAKH,@TIENKHACHTRA)
--XÓA HÓA ĐƠN
GO
CREATE PROC sp_XOAHD(@MAHD NVARCHAR(10))
AS
	DELETE [HOADON]
	WHERE MAHD=@MAHD
--SỬA HÓA ĐƠN
GO
CREATE PROC sp_SUAHD(@MAHD NVARCHAR(10), @NGAYLAP DATE, @PTTHANHTOAN NVARCHAR(15), 
					   @MANV NVARCHAR(10), @MAKH NVARCHAR(10), @TIENKHACHTRA INT)
AS
	UPDATE [HOADON]
	SET NGAYLAP=@NGAYLAP, PTTHANHTOAN=@PTTHANHTOAN, MANV=@MANV,MAKH=@MAKH, TIENKHACHTRA=@TIENKHACHTRA
	WHERE MAHD=@MAHD
--LẤY DANH SÁCH HÓA ĐƠN
GO
CREATE PROC sp_LAYDSHD
AS
	SELECT * FROM [HOADON]

---------------------------------------------------PROCEDURE BẢNG HÓA ĐƠN CHI TIẾT
--THÊM HÓA ĐƠN CHI TIẾT
GO
CREATE PROC sp_THEMHDCT(@MAHD NVARCHAR(10), @MAHH NVARCHAR(10), @SOLUONG INT)
AS 
	INSERT INTO [HDCHITIET](MAHD,MAHH,SOLUONG) VALUES (@MAHD,@MAHH,@SOLUONG)

--XÓA HÓA ĐƠN CHI TIẾT
GO
CREATE PROC sp_XOAHDCT(@MAHD NVARCHAR(10))
AS
	DELETE [HDCHITIET]
	WHERE MAHD=@MAHD
--SỬA HDCHITIET
GO
CREATE PROC sp_SUAHDCT(@MAHD NVARCHAR(10), @MAHH NVARCHAR(10), @SOLUONG INT)
AS
	UPDATE [HDCHITIET]
	SET MAHH=@MAHH, SOLUONG=@SOLUONG
	WHERE MAHD=@MAHD

--LẤY DANH SÁCH HÓA ĐƠN CHI TIẾT
GO
CREATE PROC sp_LAYDSHDCT
AS
	SELECT hdct.MAHD, MAHH, SOLUONG, TONGTIENHH FROM [HDCHITIET] hdct, [HOADON] hd where hdct.MAHD = hd.MAHD

GO
CREATE PROC sp_LAYHDCT(@MAHD NVARCHAR(10))
AS
	SELECT  MAHD, MAHH, SOLUONG, TONGTIENHH FROM [HDCHITIET] WHERE @MAHD=MAHD

--GO
--CREATE PROC sp_LAYHDCT2(@MAHD NVARCHAR(10), @MAHH NVARCHAR(10))
--AS
--	SELECT  MAHD, hdct.MAHH, hh.TENHH, hh.DONGIA,hdct.SOLUONG, TONGTIENHH FROM [HDCHITIET] hdct, [HANGHOA] hh 
--	WHERE @MAHD=MAHD AND @MAHH= hh.MAHH
GO
CREATE PROC sp_LAYTHONGTINHH(@MAHH NVARCHAR(10))
AS
	SELECT TENHH, DONGIA FROM [HANGHOA] WHERE @MAHH=MAHH

--DROP PROC sp_LAYHDCT
--GO
--exec sp_ThemKH N'KH001',N'TRƯƠNG HOÀNG MINH', N'DƯƠNG',N'0365435355',N'208, Đ.Dương Đình Nghệ, P.Phú Thọ, TP.Thủ Dầu Một, Tỉnh Bình Dương',6742
GO
exec sp_LAYDSHD
--exec sp_LAYDSHDCT
exec sp_LAYDSHH
exec sp_LayDSKH
exec sp_LAYDSNV
exec sp_LayNCC
GO
exec sp_LAYHDCT @MAHD = N'HD00';

exec sp_LAYTHONGTINHH @MAHH=N'HH00';