--TẠO DB
GO
CREATE DATABASE QUANLYSTCOOPFOOD
SET DATEFORMAT DMY;
--DROP DATABASE QUANLYSTCOOPFOOD
GO
USE QUANLYSTCOOPFOOD
-------------------------------------------------TẠO BẢNG
GO
--1. TẠO BẢNG KHACHHANG
CREATE TABLE [KHACHHANG] (MAKH NVARCHAR(10) NOT NULL, HOKH NVARCHAR(30) NOT NULL, TENKH NVARCHAR(10) NOT NULL, SDT NVARCHAR(15) NOT NULL,
						  DCHI NVARCHAR(200) NOT NULL, DIEM INT NOT NULL, LOAIKH NVARCHAR(10) NULL)

GO
--2. TẠO BẢNG NHANVIEN
CREATE TABLE [NHANVIEN] (MANV NVARCHAR(10) NOT NULL, HONV NVARCHAR(30) NOT NULL, TENNV NVARCHAR(10) NOT NULL, NGSINH DATE NOT NULL, 
						 PHAI NVARCHAR(10) NOT NULL, DCHI NVARCHAR(200) NOT NULL, SDT NVARCHAR(15) NOT NULL, CMND NVARCHAR(9) NOT NULL)

GO
--3. TẠO BẢNG NHACUNGCAP
CREATE TABLE [NHACUNGCAP] (MANCC NVARCHAR(10) NOT NULL, TENNCC NVARCHAR(200) NOT NULL, 
						   DCHI NVARCHAR(200) NOT NULL, SDT NVARCHAR(15) NOT NULL, EMAIL NVARCHAR(50) NULL)
GO
--4. TẠO BẢNG HANGHOA
CREATE TABLE [HANGHOA] (MAHH NVARCHAR(10) NOT NULL, MANCC NVARCHAR(10) NOT NULL,TENHH NVARCHAR(100) NOT NULL, LOAIHH NVARCHAR(40) NOT NULL, 
						SOLUONG INT NOT NULL, DONGIA INT NOT NULL, NGAYSX DATE NOT NULL, HANSD DATE NOT NULL)

GO
--5. TẠO BẢNG HDCHITIET
CREATE TABLE [HDCHITIET] (MAHD NVARCHAR(10) NOT NULL, MAHH NVARCHAR(10) NOT NULL, 
					   SOLUONG INT NOT NULL, TONGTIENHH INT NOT NULL)

GO
--6. TẠO BẢNG HOADON
CREATE TABLE [HOADON] (MAHD NVARCHAR(10) NOT NULL, NGAYLAP DATE NOT NULL, PTTHANHTOAN NVARCHAR(15) NOT NULL, 
					   MANV NVARCHAR(10) NOT NULL, MAKH NVARCHAR(10) NOT NULL, TIENKHACHTRA INT NULL,
					   TONGTIEN INT NULL, TIENTHUA INT NULL)

-------------------------------------------------TẠO CHỨC NĂNG CHO CỘT TỰ ĐỘNG TÍNH TOÁN

-- KHACHHANG
GO
CREATE FUNCTION [dbo].FUNC_KHACHHANG_COMPUTED_LOAIKH(@DIEM INT)
RETURNS NVARCHAR(10)
WITH SCHEMABINDING AS
BEGIN
	DECLARE @LOAIKH NVARCHAR(10);
    IF @DIEM < 500
	BEGIN
		SET @LOAIKH = N'THƯỜNG'
	END
	ELSE IF @DIEM < 1000
	BEGIN
		SET @LOAIKH = N'VIP1'
	END
	ELSE IF @DIEM < 5000
	BEGIN
		SET @LOAIKH = N'VIP2'
	END
	ELSE IF @DIEM < 15000
	BEGIN
		SET @LOAIKH = N'VIP3'
	END
	ELSE IF @DIEM < 30000
	BEGIN
		SET @LOAIKH = N'VIP4'
	END
	ELSE
	BEGIN
		SET @LOAIKH = N'VIP5'
	END
	RETURN @LOAIKH;
END


GO
ALTER TABLE [KHACHHANG] DROP COLUMN LOAIKH
ALTER TABLE [KHACHHANG] ADD LOAIKH AS [dbo].FUNC_KHACHHANG_COMPUTED_LOAIKH(DIEM) PERSISTED

-- HDCHITIET
GO
CREATE FUNCTION [dbo].FUNC_HDCHITIET_COMPUTED_TONGTIENHH(@MAHH NVARCHAR(10), @SOLUONG INT)
RETURNS INT
BEGIN
    RETURN (SELECT TOP 1 DONGIA FROM [dbo].[HANGHOA] WHERE MAHH = @MAHH) * @SOLUONG;
END

GO
ALTER TABLE [HDCHITIET] DROP COLUMN TONGTIENHH
ALTER TABLE [HDCHITIET] ADD TONGTIENHH AS [dbo].FUNC_HDCHITIET_COMPUTED_TONGTIENHH(MAHH, SOLUONG)

-- HOADON
GO
CREATE FUNCTION [dbo].FUNC_HOADON_COMPUTED_TONGTIEN(@MAHD NVARCHAR(10))
RETURNS INT
WITH SCHEMABINDING AS
BEGIN
    RETURN (SELECT SUM(TONGTIENHH) FROM [dbo].[HDCHITIET] WHERE MAHD = @MAHD);
END

GO
ALTER TABLE [HOADON] DROP COLUMN TONGTIEN
ALTER TABLE [HOADON] ADD TONGTIEN AS [dbo].FUNC_HOADON_COMPUTED_TONGTIEN(MAHD) --PERSISTED

-- HOADON TIENTHUA
GO
CREATE FUNCTION [dbo].FUNC_HOADON_COMPUTED_TIENTHUA(@MAHD NVARCHAR(10), @TIENKHACHTRA INT)
RETURNS INT
WITH SCHEMABINDING AS -- WITH SCHEMABINDING , RETURNS NULL ON NULL input AS
BEGIN
	DECLARE @TONGTIEN INT;
	DECLARE @TIENTHUA INT;
	SET @TONGTIEN = (SELECT SUM(TONGTIENHH) FROM [dbo].[HDCHITIET] WHERE MAHD = @MAHD)

    IF @TIENKHACHTRA > @TONGTIEN
	BEGIN
		SET @TIENTHUA = @TIENKHACHTRA - @TONGTIEN
	END
	ELSE
	BEGIN
		SET @TIENTHUA = 0
	END
    RETURN @TIENTHUA;
END

GO
ALTER TABLE [HOADON] DROP COLUMN TIENTHUA
ALTER TABLE [HOADON] ADD TIENTHUA AS [dbo].FUNC_HOADON_COMPUTED_TIENTHUA(MAHD, TIENKHACHTRA) --PERSISTED
-------------------------------------------------RÀNG BUỘC TOÀN VẸN
-------------------------------------------------KHÓA CHÍNH
--1. BẢNG KHACHHANG
GO
ALTER TABLE [KHACHHANG] ADD CONSTRAINT PK_KHACHHANG PRIMARY KEY (MAKH)
--2. BẢNG NHANVIEN
GO
ALTER TABLE [NHANVIEN] ADD CONSTRAINT PK_NHANVIEN PRIMARY KEY (MANV)
--3. BẢNG HOADON
GO
ALTER TABLE [HOADON] ADD CONSTRAINT PK_HOADON PRIMARY KEY (MAHD)

--4. BẢNG HANGHOA
GO
ALTER TABLE [HANGHOA] ADD CONSTRAINT PK_HANGHOA PRIMARY KEY (MAHH)
--5. BẢNG NHACUNGCAP
GO
ALTER TABLE [NHACUNGCAP] ADD CONSTRAINT PK_NHACUNGCAP PRIMARY KEY (MANCC)

-------------------------------------------------KHÓA NGOẠI
--1.BẢNG HOADON
GO
ALTER TABLE [HOADON] ADD CONSTRAINT FK_HD_KH FOREIGN KEY (MAKH) REFERENCES [KHACHHANG](MAKH)

GO
ALTER TABLE [HOADON] ADD CONSTRAINT FK_HD_NV FOREIGN KEY (MANV) REFERENCES [NHANVIEN](MANV)
--2. BẢNG CHITIETHOADON
GO
ALTER TABLE [HDCHITIET] ADD CONSTRAINT FK_CTHD_HD FOREIGN KEY (MAHD) REFERENCES [HOADON](MAHD)
GO
ALTER TABLE [HDCHITIET] ADD CONSTRAINT FK_CTHP_HH FOREIGN KEY (MAHH) REFERENCES [HANGHOA](MAHH)
--2. BẢNG NHACUNGCAP
GO
ALTER TABLE [HANGHOA] ADD CONSTRAINT FK_HH_NCC FOREIGN KEY (MANCC) REFERENCES [NHACUNGCAP](MANCC)

-------------------------------------------------MIỀN GIÁ TRỊ
GO
ALTER TABLE [NHANVIEN] ADD CHECK (PHAI = N'NAM' OR PHAI = N'NỮ')
GO
ALTER TABLE [NHANVIEN] ADD CHECK (2022-YEAR(NGSINH) >= 18)
GO
ALTER TABLE [HANGHOA] ADD CHECK (NGAYSX < HANSD)
--GO